openapi: "3.0.0"
info:
  title: "DeliverIt API"
  version: "1.0"
  description: "This API allows you to manage delivery orders and their associated order-groups. Features include creating and retrieving both order-groups and individual delivery orders."
  
servers:
  - url: "http://external.deliveritmy.com"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: "JWT"

  schemas:
    Location:
      type: object
      description: "The Location Object represents geographical coordinates."
      properties:
        longitude:
          type: number
          format: float
          description: "The longitude coordinate of the location."
        latitude:
          type: number
          format: float
          description: "The latitude coordinate of the location."

security:
  - BearerAuth: []

paths:
  /order-groups:
    post:
      summary: "Creates a new order group for delivery."
      description: "Use this endpoint to create a new order group for delivery tasks."
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "The name or description of the order group."
                pickup_location:
                  $ref: "#/components/schemas/Location"
      responses:
        '200':
          description: "Successful operation."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "Unique identifier for the newly created order group."
                  name:
                    type: string
                    description: "The name or description of the order group."
                  status:
                    type: string
                    description: "Current status of the order group."
                  created_at:
                    type: string
                    description: "Timestamp indicating when the order group was created."
                  updated_at:
                    type: string
                    description: "Timestamp indicating the last time the order group was updated."

  /order-groups/{group_id}:
    get:
      summary: "Retrieves details of a specific order-group."
      description: "Use this endpoint to retrieve details of a specific order group by its unique identifier."
      security:
        - BearerAuth: []
      parameters:
        - name: "group_id"
          in: "path"
          required: true
          description: "ID of the order-group to retrieve."
          schema:
            type: integer
      responses:
        '200':
          description: "Successful operation."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "Unique identifier for the order group."
                  name:
                    type: string
                    description: "The name or description of the order group."
                  created_at:
                    type: string
                    description: "Timestamp indicating when the order group was created."
                  updated_at:
                    type: string
                    description: "Timestamp indicating the last time the order group was updated."

  /order-groups/{group_id}/orders:
    post:
      summary: "Creates a new delivery order within a specific order-group."
      security:
        - BearerAuth: []
      parameters:
        - name: "group_id"
          in: "path"
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: "Delivery address."
                status:
                  type: string
                  description: "Delivery status (e.g., 'Pending', 'Delivered')."
      responses:
        '200':
          description: "Successfully created a new delivery order."

  /order-groups/{group_id}/orders/{id}:
    get:
      summary: "Retrieves details of a specific delivery order within a given order-group."
      security:
        - BearerAuth: []
      parameters:
        - name: "group_id"
          in: "path"
          required: true
          schema:
            type: integer
        - name: "id"
          in: "path"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Successfully retrieved the details of the specific delivery order."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "Unique identifier for the delivery order."
                  address:
                    type: string
                    description: "Delivery address."
                  status:
                    type: string
                    description: "Delivery status."
                  created_at:
                    type: string
                    description: "Timestamp indicating when the delivery order was created."
                  updated_at:
                    type: string
                    description: "Timestamp indicating the last time the delivery order was updated."